openapi: 3.0.0

info:
  version: 1.0.0
  title: ""
  description: "Note: Leaderboard stats are only available for PC players."
servers:
  - url: https://api.pubg.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "steam"
        default: steam

security:
  - ApiKeyAuth: []

paths:
  /leaderboards/{gameMode}:
    $ref: './paths/index.yml#/leaderboards'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    leaderboards:
      $ref: 'schemas/index.yml#/leaderboards'
