openapi: 3.0.0

info:
  version: 1.0.0
  title: ""
  description: "Note: Lifetime stats are only available for PC players and begin with season division.bro.official.pc-2018-01."
servers:
  - url: https://api.pubg.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "steam"
        - "kakao"
        default: steam

security:
  - ApiKeyAuth: []

paths:
  /players/{accountId}/seasons/lifetime:
    $ref: './paths/index.yml#/lifetime'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    gameModeStats:
      $ref: 'schemas/index.yml#/gameModeStats'
    matchList:
      $ref: 'schemas/index.yml#/matchList'
