openapi: 3.0.0

info:
  version: 1.0.0
  title: ""
  description: Notes:<br><br>
    - The plaform shard should be used to get matches. The platform-region shard is deprecated for the matches endpoint.<br><br>
    - The data retention period is 14 days. Match data older than 14 days will not be available.<br><br>
    - Any property with \"N/A\" as its description is not currently in use."
servers:
  - url: https://api.pubg.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "steam"
        - "psn"
        - "xbox"
        - "tournament"
        - "kakao"
        default: steam

security:
  - ApiKeyAuth: []

paths:
  /matches/{id}:
    $ref: './paths/index.yml#/match'

components:
  schemas:
    match:
      $ref: 'schemas/index.yml#/match'
    roster:
      $ref: 'schemas/index.yml#/roster'
    participant:
      $ref: 'schemas/index.yml#/participant'
    asset:
      $ref: 'schemas/index.yml#/asset'
