openapi: 3.0.0

info:
  version: 1.0.0
  title: ""
  description: Notes:<br><br>
    - The platform shard should be used at the players endpoint. The platform-region shard is deprecated for the players endpoint and the API will respond by returning data for all regions for the platform.<br><br>
    - Any property with \"N/A\" as its description is not currently in use."


servers:
  - url: https://api.pubg.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "steam"
        - "psn"
        - "xbox"
        - "kakao"
        default: steam

security:
  - ApiKeyAuth: []

paths:
  /players:
    $ref: './paths/index.yml#/players'

  /players/{accountId}:
    $ref: './paths/index.yml#/player'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    player:
      $ref: 'schemas/index.yml#/player'
    matchList:
      $ref: 'schemas/index.yml#/matchList'
