openapi: 3.0.0

info:
  version: 1.0.0
  title: ""
  description: ""
servers:
  - url: https://api.pubg.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "steam"
        - "console"
        - "psn"
        - "xbox"
        - "kakao"
        default: steam

security:
  - ApiKeyAuth: []

paths:
  /players/{accountId}/weapon_mastery:
    $ref: './paths/index.yml#/weaponMastery'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    weaponMastery:
      $ref: './schemas/index.yml#/weaponMastery'
    weaponSummary:
      $ref: './schemas/index.yml#/weaponSummary'
